name: mohamed_chocolatine
on:
  push:
    branches-ignore:
        - ga-ignore-
  pull_request:
    branches-ignore:
        - ga-ignore-
    env:
        MIRROR_URL: https://github.com/EpitechPromo2026/B-DOP-200-COT-2-1-chocolatine-mohamed.onifade.git
        EXECUTABLES: 101pong

  workflow_dispatch:

jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3

     #- name: Unwanted file detected
       #run: |
       #var=$(find . -type f \( -name "*.o" -o -name "*~" -o -name "#*" -o -name "*.a" -o -name "*.so" -o -name "*.gcda" -o -name "*.gcov" -o -name "tmp" \))
       #echo $var
     - name: Run a multi-line script
       run: |
         (find . -type f \( -name "*.o" -o -name "*~" -o -name "#*" -o -name "*.a" -o -name "*.so" -o -name "*.gcda" -o -name "*.gcov" -o -name "tmp" \))
         echo Add other actions to build,
         echo test, and deploy your project.
